name: Run test

on:
  pull_request_target:
    types: [opened, synchronize]
    branches:
      - develop
      - main

permissions:
  contents: write
  actions: read
  checks: write

jobs:
  publish:
    name: Publish
    # needs: e2e_tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      - name: Authenticate with npm
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: 'Version and publish'
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"
          echo "Test change 1" >> file.txt
          git add file.txt
          git commit -m "Update file.txt with test change"
          git push origin HEAD:develop
